<?php

namespace App\Models;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Str;

class Post extends Model
{
    public const TYPE_POST="post";
    public const TYPE_PRODUCT="product";
    public const TYPE_STUFF="stuff";
    public const TYPE_NEW="news";
    public const TYPE_SETTING="setting";






    protected $fillable = ['title', 'subtitle', 'body', 'slug', 'file_id', 'status', 'type', 'link'];


    public function file()
    {
        return $this->belongsTo(Files::class);
    }

    public function posts()
    {
        return $this->hasMany(Post::class,'parent_id','id')->orderBy('updated_at','DESC');
    }
    public function setSlugAttribute($value)
    {
        $this->attributes['slug'] = empty($value) ?
            Str::slug($this->attributes['title'])
            : str_replace(' ', '-', $value);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::created(function ($model) {
            $model->slug .= $model->id;
            $model->save();
        });
    }

    public function scopeLatestFirst($query)
    {
        return $query->orderBy('updated_at', 'desc');
    }


}
